### ISSUE TITLE
delete this repo

### ISSUE THREAD

**Issue by ZasticBradyn** [Hansitopy/blooket-hack#1]
hey, please delete this repo, it has code that gliz would not like being public, or he will file a report to github of this repo.

**Comment by Hansitopy** [comment]
It doesnt belong to gliz anymore it belongs to github and school cheats

**Comment by Hansitopy** [comment]
Also gliz said that he is no longer associated i will remove him from the read me files and if he tells me to delete i will.

**Comment by Hansitopy** [comment]
He also didnt make most of the scripts to my understanding there were globaly contrubited to schoolchetes.net

**Comment by Hansitopy** [comment]
funny how u have a exact copy of gilz's work on your github even tho he "doesnt want it public".

**Comment by ZasticBradyn** [comment]
> funny how u have a exact copy of gilz's work on your github even tho he "doesnt want it public".

their is un-obfusocated code in this repo, therefore if the owner of blooket found it all of the hacks will get patched

**Comment by ZasticBradyn** [comment]
> He also didnt make most of the scripts to my understanding there were globaly contrubited to schoolchetes.net

also no, he made all the scripts.

**Comment by ZasticBradyn** [comment]
> Also gliz said that he is no longer associated i will remove him from the read me files and if he tells me to delete i will.

he told me to give you his discord gliz#0777 add him, then tell me your discord.

**Comment by glixzzy** [comment]
> It doesnt belong to gliz anymore it belongs to github and school cheats

> Also gliz said that he is no longer associated i will remove him from the read me files and if he tells me to delete i will.

> He also didnt make most of the scripts to my understanding there were globaly contrubited to schoolchetes.net

No, I only say I'm not associated so I don't get in legal trouble. The scripts are all mine. I created them myself. schoolcheats is owned by my friend. And yes I really would like you to delete this repo. If you refuse a DMCA takedown request will be filed to GitHub. Just like all those 10 other repos that were taken down. 

Thank you for understanding,
glixzzy
